### ISSUE TITLE
VC JWT Subject claim

### ISSUE THREAD

**Issue by clehner** [transmute-industries/verifiable-data#123] opened 2021-11-16 18:14 UTC
JWT Verifiable Credential output in JWS-Test-Suite in some cases has claim `"sub":{}`:
https://github.com/decentralized-identity/JWS-Test-Suite/blob/5084057e83142f17a7656ca8f9d439eea97f08d3/implementations/transmute/credential-0--key-0-ed25519.vc-jwt.json (Edit: or a non-empty object for `sub`: https://github.com/decentralized-identity/JWS-Test-Suite/issues/54#issuecomment-1139826355)
This appears to be a conversion of an object `credentialSubject` from a verifiable credential ([credentialSubject](https://www.w3.org/TR/vc-data-model/#credential-subject)):
https://github.com/decentralized-identity/JWS-Test-Suite/blob/85e1b77be6197e21489526315fc3f5ec1e484dfe/data/credentials/credential-0.json
But the `sub` claim value is supposed to be a StringOrURI according to https://www.rfc-editor.org/rfc/rfc7519.html#section-4.1.2
In the case of `credentialSubject` without an `id` property, it might make sense to omit the `sub` claim.

**Comment by OR13** [comment] 2021-11-16 18:30
This is caused by our attempt at handling the issue discussed here: https://github.com/w3c/vc-data-model/pull/828#discussion_r749558939

The problem is "how to map a JSON-LD VC to a JWT payload"... its a stupidly simply problem, that should be addressed via normative text in the next spec or VC-JWT should be removed from the next vc data model spec.

For now, we probably need to be smart about getting `sub <= vc.credentialSubject.id or vc.credentialSubject (if its a string)`

**Comment by clehner** [comment] 2021-11-18 20:25
Related: issue about string value for credentialSubject: https://github.com/w3c/vc-data-model/issues/762.

Also there is the case of an array credentialSubject (empty, single value, or multiple values).

**Comment by OR13** [comment] 2022-03-16 15:37
I closed the other, it has less context.

**Comment by decentralgabe** [comment] 2022-03-21 16:24
also https://github.com/decentralized-identity/JWS-Test-Suite/issues/54 is a dupe

**Comment by OR13** [comment] 2023-06-29 22:58
v2 resolved this, closing

**Closed by OR13** 2023-06-29 22:58 UTC
